name: Development Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win32
          - os: macos-latest
            platform: darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun run build

      - name: Make distributables
        run: bunx electron-forge make --platform ${{ matrix.platform }}

      - name: List build outputs (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          echo "=== Build outputs ==="
          find out/make -type f | sort
          echo "=== File sizes ==="
          find out/make -type f -exec ls -lh {} \;

      - name: List build outputs (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          echo === Build outputs ===
          dir /s /b out\make
          echo === File details ===
          dir /s out\make

      - name: Upload artifacts (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-builds
          path: |
            out/make/squirrel.windows/**/*.exe
            out/make/squirrel.windows/**/*.nupkg
            out/make/squirrel.windows/**/RELEASES
          if-no-files-found: error
          retention-days: 90

      - name: Upload artifacts (macOS)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-builds
          path: |
            out/make/*.dmg
            out/make/zip/**/*.zip
            out/make/*.zip
          if-no-files-found: error
          retention-days: 90

      - name: Upload artifacts (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-builds
          path: |
            out/make/deb/**/*.deb
            out/make/rpm/**/*.rpm
            out/make/*.deb
            out/make/*.rpm
            out/make/*.AppImage
          if-no-files-found: error
          retention-days: 90

  release:
    name: Create Development Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure
        run: |
          echo "=== Artifact structure ==="
          find artifacts -type f -name "*.exe" -o -name "*.deb" -o -name "*.rpm" -o -name "*.dmg" -o -name "*.zip" | sort

      - name: Delete old development release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: development
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create Development Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: development
          name: Development Build
          body: |
            ## Latest Development Build
            
            This is an automated development build from the latest main branch.
            
            **⚠️ Warning:** This is a development build and may be unstable.
            
            ### Downloads
            - **Windows:** Download the `.exe` file
            - **macOS:** Download the `.dmg` or `.zip` file
            - **Linux:** Download the `.deb` or `.rpm` file
            
            ---
            Built from commit: ${{ github.sha }}
            Build date: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: true
          files: |
            artifacts/**/*.exe
            artifacts/**/*.deb
            artifacts/**/*.rpm
            artifacts/**/*.dmg
            artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}